### ISSUE TITLE
Unversioned gst-launch

### ISSUE THREAD

**Issue by quozl** [sugarlabs/fractionbounce#7]
Similar problem to https://github.com/sugarlabs/story/issues/10

https://github.com/sugarlabs/AEIOU/commit/79dec3b6611b8bd885909e78be2e5cbd7449cd62 may help.

**Comment by quozl** [comment]
Fixed by https://github.com/sugarlabs/fractionbounce/pull/9/commits/e85a79e0f96394cf4d88d1f298a0a0e223e53b9f in https://github.com/sugarlabs/fractionbounce/pull/9

**Comment by chimosky** [comment]
@quozl since this has been fixed in #9 should we close this

**Comment by quozl** [comment]
No, because it has not been merged yet; it is still work in progress.  It needs collaboration testing first.
